const projectData = [
    { name: 'Guess Who Infinite',
      description: 'A game of Guess Who where users can choose their own category and play with friends',
      technology: [],
      images: [],
    },
    { name: 'Shop Equal',
      description: 'A centralized interface designed to empower the Black community by directing users to Black owned businesses',
      technology: [],
      images: [],
    },
    { name: 'COVID-19 Visualizer    ',
      description: 'View data and dangers of COVID-19 throughout United States',
      technology: [],
      images: [],
    },
    { name: 'Name Rater',
      description: 'View how your name ranks amongst others',
      technology: [],
      images: [],
    },
    { name: 'Hangry',
      description: 'See what recipes you can make and what your friends',
      technology: [],
      images: [],
    },
    { name: 'Stock Simulator',
      description: 'Create an account with $5000 and watch your investments change',
      technology: [],
      images: [],
    },
    { name: 'Oh Snap',
      description: 'Social media for photographers to upload their work and gain inspiration',
      technology: [],
      images: [],
    },  
]

export default projectData;